// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/academic/v1/academic.proto

package academicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AcademicServiceClient is the client API for AcademicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcademicServiceClient interface {
	GetStudentProfile(ctx context.Context, in *GetStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfile, error)
	// Internal endpoints for Admin Service (not mapped to HTTP gateway, or mapped but protected)
	ListStudentProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListStudentProfilesResponse, error)
	CreateStudentProfile(ctx context.Context, in *CreateStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfile, error)
	DeleteStudentProfile(ctx context.Context, in *DeleteStudentProfileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateStudentProfile(ctx context.Context, in *UpdateStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfile, error)
	GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsRequest, opts ...grpc.CallOption) (*ListAttendanceResponse, error)
	SubmitLectureAttendance(ctx context.Context, in *SubmitLectureAttendanceRequest, opts ...grpc.CallOption) (*AttendanceRecord, error)
	GetLectureAttendanceForDate(ctx context.Context, in *GetLectureAttendanceForDateRequest, opts ...grpc.CallOption) (*LectureAttendanceRecord, error)
	GetLectureAttendanceForDateRange(ctx context.Context, in *GetLectureAttendanceForDateRangeRequest, opts ...grpc.CallOption) (*ListLectureAttendanceResponse, error)
	GetGrades(ctx context.Context, in *GetGradesRequest, opts ...grpc.CallOption) (*ListGradesResponse, error)
	GetGradesForClassroom(ctx context.Context, in *GetGradesForClassroomRequest, opts ...grpc.CallOption) (*ListGradesResponse, error)
	UpdateStudentGrade(ctx context.Context, in *UpdateStudentGradeRequest, opts ...grpc.CallOption) (*Grade, error)
	DeleteStudentGrade(ctx context.Context, in *DeleteStudentGradeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetClassroomsByFaculty(ctx context.Context, in *GetClassroomsByFacultyRequest, opts ...grpc.CallOption) (*ListClassroomsResponse, error)
	GetStudentsInClassroom(ctx context.Context, in *GetStudentsInClassroomRequest, opts ...grpc.CallOption) (*ListStudentsResponse, error)
	CreateClassroom(ctx context.Context, in *CreateClassroomRequest, opts ...grpc.CallOption) (*Classroom, error)
	AddStudentsToClassroom(ctx context.Context, in *AddStudentsToClassroomRequest, opts ...grpc.CallOption) (*Classroom, error)
	RemoveStudentFromClassroom(ctx context.Context, in *RemoveStudentFromClassroomRequest, opts ...grpc.CallOption) (*Classroom, error)
	GetAcademicCalendarEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListEventsResponse, error)
}

type academicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicServiceClient(cc grpc.ClientConnInterface) AcademicServiceClient {
	return &academicServiceClient{cc}
}

func (c *academicServiceClient) GetStudentProfile(ctx context.Context, in *GetStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfile, error) {
	out := new(StudentProfile)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetStudentProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) ListStudentProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListStudentProfilesResponse, error) {
	out := new(ListStudentProfilesResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/ListStudentProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) CreateStudentProfile(ctx context.Context, in *CreateStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfile, error) {
	out := new(StudentProfile)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/CreateStudentProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) DeleteStudentProfile(ctx context.Context, in *DeleteStudentProfileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/DeleteStudentProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) UpdateStudentProfile(ctx context.Context, in *UpdateStudentProfileRequest, opts ...grpc.CallOption) (*StudentProfile, error) {
	out := new(StudentProfile)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/UpdateStudentProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsRequest, opts ...grpc.CallOption) (*ListAttendanceResponse, error) {
	out := new(ListAttendanceResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetAttendanceRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) SubmitLectureAttendance(ctx context.Context, in *SubmitLectureAttendanceRequest, opts ...grpc.CallOption) (*AttendanceRecord, error) {
	out := new(AttendanceRecord)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/SubmitLectureAttendance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetLectureAttendanceForDate(ctx context.Context, in *GetLectureAttendanceForDateRequest, opts ...grpc.CallOption) (*LectureAttendanceRecord, error) {
	out := new(LectureAttendanceRecord)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetLectureAttendanceForDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetLectureAttendanceForDateRange(ctx context.Context, in *GetLectureAttendanceForDateRangeRequest, opts ...grpc.CallOption) (*ListLectureAttendanceResponse, error) {
	out := new(ListLectureAttendanceResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetLectureAttendanceForDateRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetGrades(ctx context.Context, in *GetGradesRequest, opts ...grpc.CallOption) (*ListGradesResponse, error) {
	out := new(ListGradesResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetGrades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetGradesForClassroom(ctx context.Context, in *GetGradesForClassroomRequest, opts ...grpc.CallOption) (*ListGradesResponse, error) {
	out := new(ListGradesResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetGradesForClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) UpdateStudentGrade(ctx context.Context, in *UpdateStudentGradeRequest, opts ...grpc.CallOption) (*Grade, error) {
	out := new(Grade)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/UpdateStudentGrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) DeleteStudentGrade(ctx context.Context, in *DeleteStudentGradeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/DeleteStudentGrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetClassroomsByFaculty(ctx context.Context, in *GetClassroomsByFacultyRequest, opts ...grpc.CallOption) (*ListClassroomsResponse, error) {
	out := new(ListClassroomsResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetClassroomsByFaculty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetStudentsInClassroom(ctx context.Context, in *GetStudentsInClassroomRequest, opts ...grpc.CallOption) (*ListStudentsResponse, error) {
	out := new(ListStudentsResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetStudentsInClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) CreateClassroom(ctx context.Context, in *CreateClassroomRequest, opts ...grpc.CallOption) (*Classroom, error) {
	out := new(Classroom)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/CreateClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) AddStudentsToClassroom(ctx context.Context, in *AddStudentsToClassroomRequest, opts ...grpc.CallOption) (*Classroom, error) {
	out := new(Classroom)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/AddStudentsToClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) RemoveStudentFromClassroom(ctx context.Context, in *RemoveStudentFromClassroomRequest, opts ...grpc.CallOption) (*Classroom, error) {
	out := new(Classroom)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/RemoveStudentFromClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicServiceClient) GetAcademicCalendarEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/academic.v1.AcademicService/GetAcademicCalendarEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicServiceServer is the server API for AcademicService service.
// All implementations should embed UnimplementedAcademicServiceServer
// for forward compatibility
type AcademicServiceServer interface {
	GetStudentProfile(context.Context, *GetStudentProfileRequest) (*StudentProfile, error)
	// Internal endpoints for Admin Service (not mapped to HTTP gateway, or mapped but protected)
	ListStudentProfiles(context.Context, *emptypb.Empty) (*ListStudentProfilesResponse, error)
	CreateStudentProfile(context.Context, *CreateStudentProfileRequest) (*StudentProfile, error)
	DeleteStudentProfile(context.Context, *DeleteStudentProfileRequest) (*emptypb.Empty, error)
	UpdateStudentProfile(context.Context, *UpdateStudentProfileRequest) (*StudentProfile, error)
	GetAttendanceRecords(context.Context, *GetAttendanceRecordsRequest) (*ListAttendanceResponse, error)
	SubmitLectureAttendance(context.Context, *SubmitLectureAttendanceRequest) (*AttendanceRecord, error)
	GetLectureAttendanceForDate(context.Context, *GetLectureAttendanceForDateRequest) (*LectureAttendanceRecord, error)
	GetLectureAttendanceForDateRange(context.Context, *GetLectureAttendanceForDateRangeRequest) (*ListLectureAttendanceResponse, error)
	GetGrades(context.Context, *GetGradesRequest) (*ListGradesResponse, error)
	GetGradesForClassroom(context.Context, *GetGradesForClassroomRequest) (*ListGradesResponse, error)
	UpdateStudentGrade(context.Context, *UpdateStudentGradeRequest) (*Grade, error)
	DeleteStudentGrade(context.Context, *DeleteStudentGradeRequest) (*emptypb.Empty, error)
	GetClassroomsByFaculty(context.Context, *GetClassroomsByFacultyRequest) (*ListClassroomsResponse, error)
	GetStudentsInClassroom(context.Context, *GetStudentsInClassroomRequest) (*ListStudentsResponse, error)
	CreateClassroom(context.Context, *CreateClassroomRequest) (*Classroom, error)
	AddStudentsToClassroom(context.Context, *AddStudentsToClassroomRequest) (*Classroom, error)
	RemoveStudentFromClassroom(context.Context, *RemoveStudentFromClassroomRequest) (*Classroom, error)
	GetAcademicCalendarEvents(context.Context, *emptypb.Empty) (*ListEventsResponse, error)
}

// UnimplementedAcademicServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAcademicServiceServer struct {
}

func (UnimplementedAcademicServiceServer) GetStudentProfile(context.Context, *GetStudentProfileRequest) (*StudentProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentProfile not implemented")
}
func (UnimplementedAcademicServiceServer) ListStudentProfiles(context.Context, *emptypb.Empty) (*ListStudentProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStudentProfiles not implemented")
}
func (UnimplementedAcademicServiceServer) CreateStudentProfile(context.Context, *CreateStudentProfileRequest) (*StudentProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudentProfile not implemented")
}
func (UnimplementedAcademicServiceServer) DeleteStudentProfile(context.Context, *DeleteStudentProfileRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudentProfile not implemented")
}
func (UnimplementedAcademicServiceServer) UpdateStudentProfile(context.Context, *UpdateStudentProfileRequest) (*StudentProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudentProfile not implemented")
}
func (UnimplementedAcademicServiceServer) GetAttendanceRecords(context.Context, *GetAttendanceRecordsRequest) (*ListAttendanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecords not implemented")
}
func (UnimplementedAcademicServiceServer) SubmitLectureAttendance(context.Context, *SubmitLectureAttendanceRequest) (*AttendanceRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLectureAttendance not implemented")
}
func (UnimplementedAcademicServiceServer) GetLectureAttendanceForDate(context.Context, *GetLectureAttendanceForDateRequest) (*LectureAttendanceRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLectureAttendanceForDate not implemented")
}
func (UnimplementedAcademicServiceServer) GetLectureAttendanceForDateRange(context.Context, *GetLectureAttendanceForDateRangeRequest) (*ListLectureAttendanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLectureAttendanceForDateRange not implemented")
}
func (UnimplementedAcademicServiceServer) GetGrades(context.Context, *GetGradesRequest) (*ListGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrades not implemented")
}
func (UnimplementedAcademicServiceServer) GetGradesForClassroom(context.Context, *GetGradesForClassroomRequest) (*ListGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGradesForClassroom not implemented")
}
func (UnimplementedAcademicServiceServer) UpdateStudentGrade(context.Context, *UpdateStudentGradeRequest) (*Grade, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudentGrade not implemented")
}
func (UnimplementedAcademicServiceServer) DeleteStudentGrade(context.Context, *DeleteStudentGradeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudentGrade not implemented")
}
func (UnimplementedAcademicServiceServer) GetClassroomsByFaculty(context.Context, *GetClassroomsByFacultyRequest) (*ListClassroomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassroomsByFaculty not implemented")
}
func (UnimplementedAcademicServiceServer) GetStudentsInClassroom(context.Context, *GetStudentsInClassroomRequest) (*ListStudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentsInClassroom not implemented")
}
func (UnimplementedAcademicServiceServer) CreateClassroom(context.Context, *CreateClassroomRequest) (*Classroom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClassroom not implemented")
}
func (UnimplementedAcademicServiceServer) AddStudentsToClassroom(context.Context, *AddStudentsToClassroomRequest) (*Classroom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStudentsToClassroom not implemented")
}
func (UnimplementedAcademicServiceServer) RemoveStudentFromClassroom(context.Context, *RemoveStudentFromClassroomRequest) (*Classroom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveStudentFromClassroom not implemented")
}
func (UnimplementedAcademicServiceServer) GetAcademicCalendarEvents(context.Context, *emptypb.Empty) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAcademicCalendarEvents not implemented")
}

// UnsafeAcademicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicServiceServer will
// result in compilation errors.
type UnsafeAcademicServiceServer interface {
	mustEmbedUnimplementedAcademicServiceServer()
}

func RegisterAcademicServiceServer(s grpc.ServiceRegistrar, srv AcademicServiceServer) {
	s.RegisterService(&AcademicService_ServiceDesc, srv)
}

func _AcademicService_GetStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetStudentProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetStudentProfile(ctx, req.(*GetStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_ListStudentProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).ListStudentProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/ListStudentProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).ListStudentProfiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_CreateStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).CreateStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/CreateStudentProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).CreateStudentProfile(ctx, req.(*CreateStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_DeleteStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).DeleteStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/DeleteStudentProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).DeleteStudentProfile(ctx, req.(*DeleteStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_UpdateStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).UpdateStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/UpdateStudentProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).UpdateStudentProfile(ctx, req.(*UpdateStudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetAttendanceRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetAttendanceRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetAttendanceRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetAttendanceRecords(ctx, req.(*GetAttendanceRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_SubmitLectureAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLectureAttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).SubmitLectureAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/SubmitLectureAttendance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).SubmitLectureAttendance(ctx, req.(*SubmitLectureAttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetLectureAttendanceForDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLectureAttendanceForDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetLectureAttendanceForDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetLectureAttendanceForDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetLectureAttendanceForDate(ctx, req.(*GetLectureAttendanceForDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetLectureAttendanceForDateRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLectureAttendanceForDateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetLectureAttendanceForDateRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetLectureAttendanceForDateRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetLectureAttendanceForDateRange(ctx, req.(*GetLectureAttendanceForDateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetGrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetGrades(ctx, req.(*GetGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetGradesForClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradesForClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetGradesForClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetGradesForClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetGradesForClassroom(ctx, req.(*GetGradesForClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_UpdateStudentGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).UpdateStudentGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/UpdateStudentGrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).UpdateStudentGrade(ctx, req.(*UpdateStudentGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_DeleteStudentGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).DeleteStudentGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/DeleteStudentGrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).DeleteStudentGrade(ctx, req.(*DeleteStudentGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetClassroomsByFaculty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassroomsByFacultyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetClassroomsByFaculty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetClassroomsByFaculty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetClassroomsByFaculty(ctx, req.(*GetClassroomsByFacultyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetStudentsInClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentsInClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetStudentsInClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetStudentsInClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetStudentsInClassroom(ctx, req.(*GetStudentsInClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_CreateClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).CreateClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/CreateClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).CreateClassroom(ctx, req.(*CreateClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_AddStudentsToClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStudentsToClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).AddStudentsToClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/AddStudentsToClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).AddStudentsToClassroom(ctx, req.(*AddStudentsToClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_RemoveStudentFromClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStudentFromClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).RemoveStudentFromClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/RemoveStudentFromClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).RemoveStudentFromClassroom(ctx, req.(*RemoveStudentFromClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicService_GetAcademicCalendarEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicServiceServer).GetAcademicCalendarEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.v1.AcademicService/GetAcademicCalendarEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicServiceServer).GetAcademicCalendarEvents(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicService_ServiceDesc is the grpc.ServiceDesc for AcademicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.v1.AcademicService",
	HandlerType: (*AcademicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentProfile",
			Handler:    _AcademicService_GetStudentProfile_Handler,
		},
		{
			MethodName: "ListStudentProfiles",
			Handler:    _AcademicService_ListStudentProfiles_Handler,
		},
		{
			MethodName: "CreateStudentProfile",
			Handler:    _AcademicService_CreateStudentProfile_Handler,
		},
		{
			MethodName: "DeleteStudentProfile",
			Handler:    _AcademicService_DeleteStudentProfile_Handler,
		},
		{
			MethodName: "UpdateStudentProfile",
			Handler:    _AcademicService_UpdateStudentProfile_Handler,
		},
		{
			MethodName: "GetAttendanceRecords",
			Handler:    _AcademicService_GetAttendanceRecords_Handler,
		},
		{
			MethodName: "SubmitLectureAttendance",
			Handler:    _AcademicService_SubmitLectureAttendance_Handler,
		},
		{
			MethodName: "GetLectureAttendanceForDate",
			Handler:    _AcademicService_GetLectureAttendanceForDate_Handler,
		},
		{
			MethodName: "GetLectureAttendanceForDateRange",
			Handler:    _AcademicService_GetLectureAttendanceForDateRange_Handler,
		},
		{
			MethodName: "GetGrades",
			Handler:    _AcademicService_GetGrades_Handler,
		},
		{
			MethodName: "GetGradesForClassroom",
			Handler:    _AcademicService_GetGradesForClassroom_Handler,
		},
		{
			MethodName: "UpdateStudentGrade",
			Handler:    _AcademicService_UpdateStudentGrade_Handler,
		},
		{
			MethodName: "DeleteStudentGrade",
			Handler:    _AcademicService_DeleteStudentGrade_Handler,
		},
		{
			MethodName: "GetClassroomsByFaculty",
			Handler:    _AcademicService_GetClassroomsByFaculty_Handler,
		},
		{
			MethodName: "GetStudentsInClassroom",
			Handler:    _AcademicService_GetStudentsInClassroom_Handler,
		},
		{
			MethodName: "CreateClassroom",
			Handler:    _AcademicService_CreateClassroom_Handler,
		},
		{
			MethodName: "AddStudentsToClassroom",
			Handler:    _AcademicService_AddStudentsToClassroom_Handler,
		},
		{
			MethodName: "RemoveStudentFromClassroom",
			Handler:    _AcademicService_RemoveStudentFromClassroom_Handler,
		},
		{
			MethodName: "GetAcademicCalendarEvents",
			Handler:    _AcademicService_GetAcademicCalendarEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/academic/v1/academic.proto",
}
