// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetAllUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	CreateManagedUser(ctx context.Context, in *CreateManagedUserRequest, opts ...grpc.CallOption) (*CreateManagedUserResponse, error)
	UpdateManagedUser(ctx context.Context, in *UpdateManagedUserRequest, opts ...grpc.CallOption) (*UpdateManagedUserResponse, error)
	DeleteManagedUser(ctx context.Context, in *DeleteManagedUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAuditLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAuditLogsResponse, error)
	GetSystemSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemSettings, error)
	UpdateSystemSettings(ctx context.Context, in *UpdateSystemSettingsRequest, opts ...grpc.CallOption) (*SystemSettings, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetAllUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateManagedUser(ctx context.Context, in *CreateManagedUserRequest, opts ...grpc.CallOption) (*CreateManagedUserResponse, error) {
	out := new(CreateManagedUserResponse)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/CreateManagedUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateManagedUser(ctx context.Context, in *UpdateManagedUserRequest, opts ...grpc.CallOption) (*UpdateManagedUserResponse, error) {
	out := new(UpdateManagedUserResponse)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/UpdateManagedUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteManagedUser(ctx context.Context, in *DeleteManagedUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/DeleteManagedUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetAuditLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAuditLogsResponse, error) {
	out := new(ListAuditLogsResponse)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/GetAuditLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSystemSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemSettings, error) {
	out := new(SystemSettings)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/GetSystemSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateSystemSettings(ctx context.Context, in *UpdateSystemSettingsRequest, opts ...grpc.CallOption) (*SystemSettings, error) {
	out := new(SystemSettings)
	err := c.cc.Invoke(ctx, "/admin.v1.AdminService/UpdateSystemSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations should embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	GetAllUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error)
	CreateManagedUser(context.Context, *CreateManagedUserRequest) (*CreateManagedUserResponse, error)
	UpdateManagedUser(context.Context, *UpdateManagedUserRequest) (*UpdateManagedUserResponse, error)
	DeleteManagedUser(context.Context, *DeleteManagedUserRequest) (*emptypb.Empty, error)
	GetAuditLogs(context.Context, *emptypb.Empty) (*ListAuditLogsResponse, error)
	GetSystemSettings(context.Context, *emptypb.Empty) (*SystemSettings, error)
	UpdateSystemSettings(context.Context, *UpdateSystemSettingsRequest) (*SystemSettings, error)
}

// UnimplementedAdminServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) GetAllUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedAdminServiceServer) CreateManagedUser(context.Context, *CreateManagedUserRequest) (*CreateManagedUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateManagedUser not implemented")
}
func (UnimplementedAdminServiceServer) UpdateManagedUser(context.Context, *UpdateManagedUserRequest) (*UpdateManagedUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManagedUser not implemented")
}
func (UnimplementedAdminServiceServer) DeleteManagedUser(context.Context, *DeleteManagedUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteManagedUser not implemented")
}
func (UnimplementedAdminServiceServer) GetAuditLogs(context.Context, *emptypb.Empty) (*ListAuditLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditLogs not implemented")
}
func (UnimplementedAdminServiceServer) GetSystemSettings(context.Context, *emptypb.Empty) (*SystemSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemSettings not implemented")
}
func (UnimplementedAdminServiceServer) UpdateSystemSettings(context.Context, *UpdateSystemSettingsRequest) (*SystemSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSystemSettings not implemented")
}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetAllUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateManagedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManagedUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateManagedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/CreateManagedUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateManagedUser(ctx, req.(*CreateManagedUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateManagedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManagedUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateManagedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/UpdateManagedUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateManagedUser(ctx, req.(*UpdateManagedUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteManagedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManagedUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteManagedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/DeleteManagedUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteManagedUser(ctx, req.(*DeleteManagedUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/GetAuditLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetAuditLogs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSystemSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSystemSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/GetSystemSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSystemSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateSystemSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateSystemSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.AdminService/UpdateSystemSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateSystemSettings(ctx, req.(*UpdateSystemSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUsers",
			Handler:    _AdminService_GetAllUsers_Handler,
		},
		{
			MethodName: "CreateManagedUser",
			Handler:    _AdminService_CreateManagedUser_Handler,
		},
		{
			MethodName: "UpdateManagedUser",
			Handler:    _AdminService_UpdateManagedUser_Handler,
		},
		{
			MethodName: "DeleteManagedUser",
			Handler:    _AdminService_DeleteManagedUser_Handler,
		},
		{
			MethodName: "GetAuditLogs",
			Handler:    _AdminService_GetAuditLogs_Handler,
		},
		{
			MethodName: "GetSystemSettings",
			Handler:    _AdminService_GetSystemSettings_Handler,
		},
		{
			MethodName: "UpdateSystemSettings",
			Handler:    _AdminService_UpdateSystemSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/v1/admin.proto",
}
