// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AcademicEvent struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	Date        string   `json:"date"`
	StartTime   *string  `json:"startTime,omitempty"`
	EndTime     *string  `json:"endTime,omitempty"`
	Location    *string  `json:"location,omitempty"`
	Type        *string  `json:"type,omitempty"`
	Audience    []string `json:"audience,omitempty"`
	Organizer   *string  `json:"organizer,omitempty"`
	Link        *string  `json:"link,omitempty"`
}

type Announcement struct {
	ID             string   `json:"id"`
	Title          string   `json:"title"`
	Content        string   `json:"content"`
	AuthorID       string   `json:"authorId"`
	AuthorName     *string  `json:"authorName,omitempty"`
	Timestamp      string   `json:"timestamp"`
	TargetAudience []string `json:"targetAudience,omitempty"`
	Attachments    []string `json:"attachments,omitempty"`
	IsImportant    *bool    `json:"isImportant,omitempty"`
	ExpiresAt      *string  `json:"expiresAt,omitempty"`
}

type AnnouncementInput struct {
	Title          string   `json:"title"`
	Content        string   `json:"content"`
	AuthorID       string   `json:"authorId"`
	AuthorName     *string  `json:"authorName,omitempty"`
	Timestamp      *string  `json:"timestamp,omitempty"`
	TargetAudience []string `json:"targetAudience,omitempty"`
	Attachments    []string `json:"attachments,omitempty"`
	IsImportant    *bool    `json:"isImportant,omitempty"`
	ExpiresAt      *string  `json:"expiresAt,omitempty"`
}

type AttendanceRecord struct {
	ID        string `json:"id"`
	StudentID string `json:"studentId"`
	LectureID string `json:"lectureId"`
	CourseID  string `json:"courseId"`
	Date      string `json:"date"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type AuditLog struct {
	ID          string  `json:"id"`
	Timestamp   string  `json:"timestamp"`
	Action      string  `json:"action"`
	ActorID     string  `json:"actorId"`
	ActorName   *string `json:"actorName,omitempty"`
	TargetID    *string `json:"targetId,omitempty"`
	TargetType  *string `json:"targetType,omitempty"`
	Description *string `json:"description,omitempty"`
	IPAddress   *string `json:"ipAddress,omitempty"`
}

type ChatMessage struct {
	ID         string  `json:"id"`
	SenderID   string  `json:"senderId"`
	SenderName *string `json:"senderName,omitempty"`
	ReceiverID string  `json:"receiverId"`
	Message    string  `json:"message"`
	Timestamp  string  `json:"timestamp"`
	Read       *bool   `json:"read,omitempty"`
}

type Classroom struct {
	ID             string                  `json:"id"`
	Name           string                  `json:"name"`
	CourseCode     string                  `json:"courseCode"`
	FacultyID      string                  `json:"facultyId"`
	FacultyName    string                  `json:"facultyName"`
	AcademicYear   string                  `json:"academicYear"`
	Semester       string                  `json:"semester"`
	Students       []*ClassroomStudentInfo `json:"students,omitempty"`
	InvitedFaculty []*FacultyUser          `json:"invitedFaculty,omitempty"`
}

type ClassroomInput struct {
	Name              string   `json:"name"`
	CourseCode        string   `json:"courseCode"`
	FacultyID         string   `json:"facultyId"`
	FacultyName       string   `json:"facultyName"`
	AcademicYear      string   `json:"academicYear"`
	Semester          string   `json:"semester"`
	StudentIds        []string `json:"studentIds,omitempty"`
	InvitedFacultyIds []string `json:"invitedFacultyIds,omitempty"`
}

type ClassroomStudentInfo struct {
	UID              string  `json:"uid"`
	Name             string  `json:"name"`
	Email            string  `json:"email"`
	EnrollmentNumber *string `json:"enrollmentNumber,omitempty"`
	SectionOrBatch   *string `json:"sectionOrBatch,omitempty"`
}

type FacultyUser struct {
	UID   string `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Grade struct {
	ID           string   `json:"id"`
	StudentID    string   `json:"studentId"`
	CourseID     string   `json:"courseId"`
	CourseName   string   `json:"courseName"`
	Grade        string   `json:"grade"`
	Score        *float64 `json:"score,omitempty"`
	MaxScore     *float64 `json:"maxScore,omitempty"`
	Semester     *string  `json:"semester,omitempty"`
	AcademicYear *string  `json:"academicYear,omitempty"`
	Timestamp    string   `json:"timestamp"`
}

type GradeInput struct {
	StudentID    string   `json:"studentId"`
	CourseID     string   `json:"courseId"`
	CourseName   string   `json:"courseName"`
	Grade        string   `json:"grade"`
	Score        *float64 `json:"score,omitempty"`
	MaxScore     *float64 `json:"maxScore,omitempty"`
	Semester     *string  `json:"semester,omitempty"`
	AcademicYear *string  `json:"academicYear,omitempty"`
}

type LectureAttendanceRecord struct {
	LectureID       string              `json:"lectureId"`
	CourseID        string              `json:"courseId"`
	Date            string              `json:"date"`
	TotalStudents   int32               `json:"totalStudents"`
	PresentStudents int32               `json:"presentStudents"`
	AbsentStudents  int32               `json:"absentStudents"`
	Attendance      []*AttendanceRecord `json:"attendance,omitempty"`
}

type Mutation struct {
}

type ProfileChangeRequest struct {
	ID               string  `json:"id"`
	UserID           string  `json:"userId"`
	RequestDate      string  `json:"requestDate"`
	Status           string  `json:"status"`
	RequestedChanges string  `json:"requestedChanges"`
	ReviewedBy       *string `json:"reviewedBy,omitempty"`
	ReviewDate       *string `json:"reviewDate,omitempty"`
	AdminComments    *string `json:"adminComments,omitempty"`
}

type ProfileChangeRequestInput struct {
	UserID           string `json:"userId"`
	RequestedChanges string `json:"requestedChanges"`
}

type Query struct {
}

type StudentProfile struct {
	UID                      string  `json:"uid"`
	Email                    string  `json:"email"`
	Name                     string  `json:"name"`
	PhotoURL                 *string `json:"photoUrl,omitempty"`
	PhoneNumber              *string `json:"phoneNumber,omitempty"`
	Address                  *string `json:"address,omitempty"`
	DateOfBirth              *string `json:"dateOfBirth,omitempty"`
	Gender                   *string `json:"gender,omitempty"`
	Nationality              *string `json:"nationality,omitempty"`
	EmergencyContactName     *string `json:"emergencyContactName,omitempty"`
	EmergencyContactNumber   *string `json:"emergencyContactNumber,omitempty"`
	EnrollmentNumber         *string `json:"enrollmentNumber,omitempty"`
	CourseProgram            *string `json:"courseProgram,omitempty"`
	Department               *string `json:"department,omitempty"`
	CurrentYear              *int32  `json:"currentYear,omitempty"`
	CurrentSemester          *int32  `json:"currentSemester,omitempty"`
	AcademicAdvisorName      *string `json:"academicAdvisorName,omitempty"`
	SectionOrBatch           *string `json:"sectionOrBatch,omitempty"`
	AdmissionDate            *string `json:"admissionDate,omitempty"`
	ModeOfAdmission          *string `json:"modeOfAdmission,omitempty"`
	IDCardURL                *string `json:"idCardUrl,omitempty"`
	AdmissionLetterURL       *string `json:"admissionLetterUrl,omitempty"`
	Marksheet10thURL         *string `json:"marksheet10thUrl,omitempty"`
	Marksheet12thURL         *string `json:"marksheet12thUrl,omitempty"`
	MigrationCertificateURL  *string `json:"migrationCertificateUrl,omitempty"`
	BonafideCertificateURL   *string `json:"bonafideCertificateUrl,omitempty"`
	UploadedPhotoURL         *string `json:"uploadedPhotoUrl,omitempty"`
	UploadedSignatureURL     *string `json:"uploadedSignatureUrl,omitempty"`
	ExamRegistrationStatus   *string `json:"examRegistrationStatus,omitempty"`
	AdmitCardURL             *string `json:"admitCardUrl,omitempty"`
	InternalExamTimetableURL *string `json:"internalExamTimetableUrl,omitempty"`
	ExternalExamTimetableURL *string `json:"externalExamTimetableUrl,omitempty"`
	ResultsAndGradeCardsURL  *string `json:"resultsAndGradeCardsUrl,omitempty"`
	RevaluationRequestStatus *string `json:"revaluationRequestStatus,omitempty"`
	RevaluationRequestLink   *string `json:"revaluationRequestLink,omitempty"`
	Role                     string  `json:"role"`
	ParentEmail              *string `json:"parentEmail,omitempty"`
}

type StudentProfileInput struct {
	Email                    *string `json:"email,omitempty"`
	Name                     *string `json:"name,omitempty"`
	PhotoURL                 *string `json:"photoUrl,omitempty"`
	PhoneNumber              *string `json:"phoneNumber,omitempty"`
	Address                  *string `json:"address,omitempty"`
	DateOfBirth              *string `json:"dateOfBirth,omitempty"`
	Gender                   *string `json:"gender,omitempty"`
	Nationality              *string `json:"nationality,omitempty"`
	EmergencyContactName     *string `json:"emergencyContactName,omitempty"`
	EmergencyContactNumber   *string `json:"emergencyContactNumber,omitempty"`
	EnrollmentNumber         *string `json:"enrollmentNumber,omitempty"`
	CourseProgram            *string `json:"courseProgram,omitempty"`
	Department               *string `json:"department,omitempty"`
	CurrentYear              *int32  `json:"currentYear,omitempty"`
	CurrentSemester          *int32  `json:"currentSemester,omitempty"`
	AcademicAdvisorName      *string `json:"academicAdvisorName,omitempty"`
	SectionOrBatch           *string `json:"sectionOrBatch,omitempty"`
	AdmissionDate            *string `json:"admissionDate,omitempty"`
	ModeOfAdmission          *string `json:"modeOfAdmission,omitempty"`
	IDCardURL                *string `json:"idCardUrl,omitempty"`
	AdmissionLetterURL       *string `json:"admissionLetterUrl,omitempty"`
	Marksheet10thURL         *string `json:"marksheet10thUrl,omitempty"`
	Marksheet12thURL         *string `json:"marksheet12thUrl,omitempty"`
	MigrationCertificateURL  *string `json:"migrationCertificateUrl,omitempty"`
	BonafideCertificateURL   *string `json:"bonafideCertificateUrl,omitempty"`
	UploadedPhotoURL         *string `json:"uploadedPhotoUrl,omitempty"`
	UploadedSignatureURL     *string `json:"uploadedSignatureUrl,omitempty"`
	ExamRegistrationStatus   *string `json:"examRegistrationStatus,omitempty"`
	AdmitCardURL             *string `json:"admitCardUrl,omitempty"`
	InternalExamTimetableURL *string `json:"internalExamTimetableUrl,omitempty"`
	ExternalExamTimetableURL *string `json:"externalExamTimetableUrl,omitempty"`
	ResultsAndGradeCardsURL  *string `json:"resultsAndGradeCardsUrl,omitempty"`
	RevaluationRequestStatus *string `json:"revaluationRequestStatus,omitempty"`
	RevaluationRequestLink   *string `json:"revaluationRequestLink,omitempty"`
	Role                     *string `json:"role,omitempty"`
	ParentEmail              *string `json:"parentEmail,omitempty"`
}

type SystemSettings struct {
	MaintenanceMode    bool    `json:"maintenanceMode"`
	AnnouncementBanner *string `json:"announcementBanner,omitempty"`
	RegistrationOpen   bool    `json:"registrationOpen"`
	ContactEmail       string  `json:"contactEmail"`
	LastUpdated        string  `json:"lastUpdated"`
}

type SystemSettingsInput struct {
	MaintenanceMode    *bool   `json:"maintenanceMode,omitempty"`
	AnnouncementBanner *string `json:"announcementBanner,omitempty"`
	RegistrationOpen   *bool   `json:"registrationOpen,omitempty"`
	ContactEmail       *string `json:"contactEmail,omitempty"`
}
